#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SkiaSharp.Components.Droid.Resource", IsApplication=false)]

namespace SkiaSharp.Components.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f020000
			public static int item_touch_helper_max_drag_scroll_per_frame = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int item_touch_helper_swipe_escape_max_velocity = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int item_touch_helper_swipe_escape_velocity = 2130837506;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int item_touch_helper_previous_elevation = 2130903040;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public static int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public static int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public static int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public static int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public static int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
